global using Aquality.Selenium.Browsers;
global using Aquality.Selenium.Core.Configurations;
global using Aquality.Selenium.Elements.Interfaces;
global using Aquality.Selenium.Forms;
global using Newtonsoft.Json;
global using NUnit.Framework;
global using OpenQA.Selenium;
global using RandomDataGenerator.FieldOptions;
global using RandomDataGenerator.Randomizers;
global using System.Net;
global using System.Text.RegularExpressions;
global using Task1_0.Driver;
global using Task1_0.Extensions;
global using Task1_0.Models;
global using Task1_0.Pages;
global using Task1_0.Utils;
global using TechTalk.SpecFlow;
global using Task1_0.Keys;

